# GitHub Pages Configuration
# This file configures the GitHub Pages site

# Site settings
title: Wisdom in Data - Multi-Agent LLM Data Factory
description: A revolutionary multi-agent LLM-based data factory for enhanced Table Question Answering
url: "https://wisdomindata.github.io"
# baseurl removed for username.github.io repositories

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Wisdom in Data Team"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages
  - _posts
  - assets

# SEO settings
author:
  name: Wisdom in Data Team
  email: research@wisdomindata.com
  bio: Multi-Agent LLM-Based Data Factory Research Team
  location: Global
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wisdomindata"

# Social media
social:
  name: Wisdom in Data
  links:
    - https://github.com/wisdomindata
    - https://www.wisdomindata.com

# Analytics (optional)
google_analytics: # UA-XXXXXXXXX-X 